# Generated by Django 4.1.2 on 2022-11-02 21:35

from django.db import migrations
def add_retail_skills(apps, schema_editor):
    Skill = apps.get_model('retaildr', 'Skill')
    skills=[]
    textFile = open(r'C:\Users\Joel\Documents\projects\WowPvpInfo\wowpvpinfo\retaildr\static\retailDrInfo.txt', 'r')
    byLine = textFile.readlines()
    for line in byLine:
        print(line)
        data = line.split(',')
        skill =(data[0], data[1], data[2],data[3])
        skills.append(skill)

    # skills = [
    #     ['DK', 'Gnaw', 'CS'],
    #     ['DK', 'Asphyxiate', 'CS'],
    #     ['DK', 'Hungering Cold', 'Disorient'],
    #     ['DK', 'Strangulate', 'Silence'],
    #     ['Druid', 'Bash', 'CS'],
    #     ['Druid', 'Cyclone', 'Disorient'],
    #     ['Druid', 'Entangling Roots', 'CR'],
    #     ['Druid', 'Hibernate', 'Disorient'],
    #     ['Druid', 'Maim', 'CS'],
    #     ['Druid', 'Pounce', 'CS'],
    #     ['Hunter', 'Entrapment', 'NONE'],
    #     ['Hunter', 'Freezing Trap', 'Incap'],
    #     ['Hunter', 'Pin', 'CR'],
    #     ['Hunter', 'Scare Beast', 'Fear'],
    #     ['Hunter', 'Scatter Shot', 'Disorient'],
    #     ['Hunter', 'Intimidation', 'CS'],
    #     ['Hunter', 'Ravage', 'CS'],
    #     ['Hunter', 'Silencing Shot', 'Silence'],
    #     ['Hunter', 'Sonic Blast', 'CS'],
    #     ['Hunter', 'Snatch', 'Disarm'],
    #     ['Hunter', 'Wyvern Sting', 'Incap'],
    #     ['Mage', 'Deep Freeze', 'CS'],
    #     ['Mage', 'Dragons Breath', 'Disorient'],
    #     ['Mage', 'Freeze', 'CR'],
    #     ['Mage', 'Frost Nova', 'CR'],
    #     ['Mage', 'Improved Cone of Cold', 'RR'],
    #     ['Mage', 'Impact', 'RS'],
    #     ['Mage', 'Improved Counterspell', 'Silence'],
    #     ['Mage', 'Polymorph', 'Incap'],
    #     ['Mage', 'Ring of Frost', 'Disorient'],
    #     ['Mage', 'Shattered Barrier', 'RR'],
    #     ['Mage', 'Slow', 'none'],
    #     ['Paladin', 'Hammer of Justice', 'CS'],
    #     ['Paladin', 'Holy Wrath', 'CS'],
    #     ['Paladin', 'Repentance', ''],
    #     ['Paladin', 'Turn Evil', 'Fear'],
    #     ['Paladin', 'Avengers Shield', 'Silence'],
    #     ['Priest', 'Psychic Scream', 'Fear'],
    #     ['Priest', 'Mind Control', 'None'],
    #     ['Priest', 'Psychic Horror', 'Horror'],
    #     ['Priest', 'Shackle Undead', 'Disorient'],
    #     ['Priest', 'Silence', 'Silence'],
    #     ['Rogue', 'Blind', 'Fear'],
    #     ['Rogue', 'Cheap Shot', 'Opener Stun'],
    #     ['Rogue', 'Garrote', 'Silence'],
    #     ['Rogue', 'Gouge', 'Disorient'],
    #     ['Rogue', 'Improved Kick', 'Silence'],
    #     ['Rogue', 'Kidney Shot', 'CS'],
    #     ['Rogue', 'Sap', 'Disorient'],
    #     ['Shaman', 'Bash', 'CS'],
    #     ['Shaman', 'Earths Grasp', 'CR'],
    #     ['Shaman', 'Frozen Power', 'CR'],
    #     ['Shaman', 'Frost Shock', 'None'],
    #     ['Shaman', 'Stoneclaw Totem', 'RS'],
    #     ['Shaman', 'Hex', 'Disorient'],
    #     ['Warlock', 'Banish', 'None'],
    #     ['Warlock', 'Death Coil', 'Horror'],
    #     ['Warlock', 'Fear', 'Fear'],
    #     ['Warlock', 'Howl of Terror', 'Fear'],
    #     ['Warlock', 'Intercept', 'CS'],
    #     ['Warlock', 'Seduction', 'Fear'],
    #     ['Warlock', 'Shadowfury', 'CS'],
    #     ['Warrior', 'Charge', 'None'],
    #     ['Warrior', 'Concussion Blow', 'CS'],
    #     ['Warrior', 'Gag Order', 'Silence'],
    #     ['Warrior', 'Intercept', 'CS'],
    #     ['Warrior', 'Improved Hamstring', 'RR'],
    #     ['Warrior', 'Intimidating Shout', 'Fear'],
    #     ['Warrior', 'Shockwave', 'CS'],
    #     ['Racial', 'Arcane Torrent', 'Silence'],
    #     ['Racial', 'War Stomp', 'CS'],

        

    # ]
    for skill in skills:
        Skill.objects.create(skill_id = skill[0],skill_name = skill[2],dr_cat = skill[1],class_name=skill[3])

class Migration(migrations.Migration):

    dependencies = [
        ('retaildr', '0002_skill_skill_id'),
    ]

    operations = [
        migrations.RunPython(add_retail_skills)
    ]
