# Generated by Django 4.1.2 on 2024-05-10 18:15

from django.db import migrations
def add_retail_classes(apps, schema_editor):
    Class = apps.get_model('retaildr', 'CharClass')
    classes=[]
    textFile = open(r'C:\Users\Joel\Documents\code\WowPvpInfo\wowpvpinfo\retaildr\static\retailDrClassList.txt', 'r')
    byLine = textFile.readlines()
    for line in byLine:
        print(line)
        Class.objects.create(class_name=line)


class Migration(migrations.Migration):

    dependencies = [
        ('retaildr', '0003_auto_20221107_1632'),
    ]

    operations = [
        migrations.RunPython(add_retail_classes)
    ]
